"""
Django settings for portfolio_site project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
import dj_database_url
from PIL import Image

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1d89ru^ceqqhui3)#c)7+s*x@c^qp!4$4^t(%49w4#!kr&296&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['my-portfolio-wpr8.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage', 
    'django.contrib.staticfiles',
    'cloudinary',
    'projects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_site.wsgi.application'


# Database Configuration
# settings.py

# settings.py

# settings.py
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        # இங்கு வழக்கம் போல require என்றே இருக்கட்டும்
        default='postgresql://portfolio_db_gw3r_user:NM0b5lVhcxnh7zvo9cuXyqukHU8WDwtT@dpg-d809s2po3t8c73dir0q0-a.virginia-postgres.render.com/portfolio_db_gw3r?sslmode=require',
        conn_max_age=600
    )
}

# இதுதான் ரகசியம்: Render-க்குத் தேவையான துல்லியமான SSL கட்டமைப்பு
DATABASES['default']['OPTIONS'] = {
    'sslmode': 'require',
}
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static Files Configuration (CSS, JavaScript)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Cloudinary Credentials Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dkoz3k7gp',
    'API_KEY': '568195923992155',
    'API_SECRET': 'i5xCtubrqsGYwXdG0NBdcJMvRWU',
    'RESOURCE_TYPE': 'auto',
}

# ஏதேனும் ஒரு ஸ்டேடிக் ஃபைல் விடுபட்டிருந்தாலும் பில்ட் ஃபெயில் ஆகாமல் தடுத்துவிடும்
WHITENOISE_MANIFEST_STRICT = False
# Django 6.0 Unified Storage Management
# Django 6.0-க்கான ஸ்டோரேஜ் கட்டமைப்பு
# Django 6.0 மற்றும் Cloudinary இணக்கமான இறுதி ஸ்டோரேஜ் கட்டமைப்பு
STORAGES = {
    # மீடியா ஃபைல்கள் Cloudinary-க்கு செல்லும்
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    # ஸ்டேடிக் ஃபைல்களை எரர் இல்லாமல் WhiteNoise கையாள எளிய ஸ்டோரேஜ்:
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

# பழைய எரர் தரும் வேரியபிள்களை மாற்றி புதிய எளிய ஸ்டோரேஜைக் காட்டுகிறோம்
STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'


# Miscellaneous Settings
IMAGE_CROPPING_JQUERY_URL = None
Image.MAX_IMAGE_PIXELS = None